package sdk

import (
	"time"
)

const (
	TOPIC_STATUS   = "VCU/+/STS"
	TOPIC_REPORT   = "VCU/+/RPT"
	TOPIC_COMMAND  = "VCU/+/CMD"
	TOPIC_RESPONSE = "VCU/+/RSP"
)

const (
	QOS_SUB_STATUS   = 1
	QOS_SUB_REPORT   = 1
	QOS_SUB_COMMAND  = 1
	QOS_SUB_RESPONSE = 2
	QOS_PUB_COMMAND  = 2
	QOS_CMD_FLUSH    = 1
)

const (
	PREFIX_ACK      = "@A"
	PREFIX_REPORT   = "@T"
	PREFIX_COMMAND  = "@C"
	PREFIX_RESPONSE = "@S"
)

const BMS_PACK_MAX = 2
const MESSAGE_LEN_MAX = 200
const SPEED_KPH_MAX = 110

const (
	FINGERPRINT_ID_MIN = 1
	FINGERPRINT_ID_MAX = 5
)

const (
	// TODO: check range in TATC datasheet
	MCU_DISCUR_MIN = 1
	MCU_DISCUR_MAX = 32767
)

const (
	// TODO: check range in TATC datasheet
	MCU_TORQUE_MIN = 7
	MCU_TORQUE_MAX = 3276
)

const (
	USSD_LENGTH_MIN = 3
	USSD_LENGTH_MAX = 20
)

const REPORT_REALTIME_DURATION = -5 * time.Second
const EEPROM_LOW_CAPACITY_PERCENT = 90
const BATTERY_BACKUP_LOW_MV = 3300
const NET_LOW_SIGNAL_PERCENT = 20
const BMS_LOW_CAPACITY_PERCENT = 20
const STACK_OVERFLOW_BYTE_MIN = 50

const (
	DEFAULT_CMD_TIMEOUT = 10 * time.Second
	DEFAULT_ACK_TIMEOUT = 8 * time.Second
)

const (
	REPORT_INTERVAL_MIN = time.Duration(5) * time.Second
	REPORT_INTERVAL_MAX = time.Duration(^uint16(0)) * time.Second
)

const (
	GPS_DOP_MIN = 5
	GPS_LNG_MIN = 95.011198
	GPS_LNG_MAX = 141.020354
	GPS_LAT_MIN = -11.107187
	GPS_LAT_MAX = 5.90713
)

const VCU_EVENTS_MAX = 7
const (
	VCU_NET_SOFT_RESET VcuEvent = iota + 0
	VCU_NET_HARD_RESET
	VCU_REMOTE_MISSING
	VCU_BIKE_FALLEN
	VCU_BIKE_MOVED
	VCU_BMS_ERROR
	VCU_MCU_ERROR
)

const BMS_FAULTS_MAX = 12
const (
	BMS_DISCHARGE_OVER_CURRENT BmsFault = iota + 0
	BMS_CHARGE_OVER_CURRENT
	BMS_SHORT_CIRCUIT
	BMS_DISCHARGE_OVER_TEMPERATURE
	BMS_DISCHARGE_UNDER_TEMPERATURE
	BMS_CHARGE_OVER_TEMPERATURE
	BMS_CHARGE_UNDER_TEMPERATURE
	BMS_UNDER_VOLTAGE
	BMS_OVER_VOLTAGE
	BMS_OVER_DISCHARGE_CAPACITY
	BMS_UNBALANCE
	BMS_SYSTEM_FAILURE
)

const MCU_POST_FAULTS_MAX = 32
const MCU_RUN_FAULTS_MAX = 32
const (
	MCU_POST_HW_DESATURATION McuFault = iota + 0
	MCU_POST_HW_OVER_CURRENT
	MCU_POST_ACCEL_SHORTED
	MCU_POST_ACCEL_OPEN
	MCU_POST_CURRENT_LOW
	MCU_POST_CURRENT_HIGH
	MCU_POST_MOD_TEMP_LOW
	MCU_POST_MOD_TEMP_HIGH
	MCU_POST_PCB_TEMP_LOW
	MCU_POST_PCB_TEMP_HIGH
	MCU_POST_GATE_TEMP_LOW
	MCU_POST_GATE_TEMP_HIGH
	MCU_POST_5V_LOW
	MCU_POST_5V_HIGH
	MCU_POST_12V_LOW
	MCU_POST_12V_HIGH
	MCU_POST_2v5_LOW
	MCU_POST_2v5_HIGH
	MCU_POST_1v5_LOW
	MCU_POST_1v5_HIGH
	MCU_POST_DCBUS_VOLT_HIGH
	MCU_POST_DCBUS_VOLT_LOW
	MCU_POST_PRECHARGE_TO
	MCU_POST_PRECHARGE_FAIL
	MCU_POST_EE_CHECKSUM_INVALID
	MCU_POST_EE_DATA_OUT_RANGE
	MCU_POST_EE_UPDATE_REQ
	MCU_POST_RESERVED_1
	MCU_POST_RESERVED_2
	MCU_POST_RESERVED_3
	MCU_POST_BRAKE_SHORTED
	MCU_POST_BRAKE_OPEN

	MCU_RUN_OVER_SPEED
	MCU_RUN_OVER_CURRENT
	MCU_RUN_OVER_VOLTAGE
	MCU_RUN_INV_OVER_TEMP
	MCU_RUN_ACCEL_SHORTED
	MCU_RUN_ACCEL_OPEN
	MCU_RUN_DIRECTION_FAULT
	MCU_RUN_INV_TO
	MCU_RUN_HW_DESATURATION
	MCU_RUN_HW_OVER_CURRENT
	MCU_RUN_UNDER_VOLTAGE
	MCU_RUN_CAN_LOST
	MCU_RUN_MOTOR_OVER_TEMP
	MCU_RUN_RESERVER_1
	MCU_RUN_RESERVER_2
	MCU_RUN_RESERVER_3
	MCU_RUN_BRAKE_SHORTED
	MCU_RUN_BRAKE_OPEN
	MCU_RUN_MODA_OVER_TEMP
	MCU_RUN_MODB_OVER_TEMP
	MCU_RUN_MODC_OVER_TEMP
	MCU_RUN_PCB_OVER_TEMP
	MCU_RUN_GATE1_OVER_TEMP
	MCU_RUN_GATE2_OVER_TEMP
	MCU_RUN_GATE3_OVER_TEMP
	MCU_RUN_CURRENT_FAULT
	MCU_RUN_RESERVER_4
	MCU_RUN_RESERVER_5
	MCU_RUN_RESERVER_6
	MCU_RUN_RESERVER_7
	MCU_RUN_RESOLVER_FAULT
	MCU_RUN_INV_DISCHARGE
)
